sudo: required
services:
  - docker
before_install:
  - docker build -t amit1300/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true  amit1300/docker-react npm run test -- --coverage

