sudo: required
services:
  - docker
before_install:
  - docker build -t amit1300/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true  amit1300/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-app"
  env: "React-app-env"
  bucket_name: "elasticbeanstalk-ap-south-1-160053629525"
  bucket_path: "react-app"
  access_key_id: $ACCESSKEYID
  secret_access_key: "SECRETACCESSKEY"
  on:
    branch: master

